name: Silence
main: feildmaster.silence.Silence
version: 1.3.2
author: feildmaster

commands:
  silence:
    description: Toggle chat listening
    aliases:
      - quiet
  silence-all:
    description: Silence the server
    aliases:
      - quiet-all

permissions:
  silence.bypass:
    description: Bypasses silence-all (Your chat will go through)
  silence.admin:
    description: Allows using silence-all
